### ISSUE TITLE
mapgen.lua:122: attempt to compare nil with number

### ISSUE THREAD

**Issue by mk-pmb** [minetest-mods/nether#36]
Using current master (89a4676):

```text
ERROR[Main]: ModError: Failed to load and run script from …/mods/nether/init.lua:
ERROR[Main]: …/mods/nether/mapgen.lua:122: attempt to compare nil with number
ERROR[Main]: stack traceback:
ERROR[Main]:       …/mods/nether/mapgen.lua:122: in function 'override_underground_biomes'
ERROR[Main]:       …/mods/nether/mapgen.lua:152: in main chunk
ERROR[Main]:       [C]: in function 'dofile'
ERROR[Main]:       …/mods/nether/init.lua:122: in main chunk
ERROR[Main]: Check debug.txt for details.
ACTION[Main]: Server: Shutting down
```

I added debug code to obtain the effective values:
> number:31000 > number:-11000 && nil:nil < number:-5000 ?

The bug only occurrs with other mods, but I have too many to disect which one causes the conflict. I'd prefer we have a safe fallback here, but I'm not sure which decision would err on the safe side.

**Comment by mk-pmb** [comment]
It seems to only occurr if the `grave` module is loaded as well.

**Comment by Treer** [comment]
lol [I think that's an L instead of a one](https://github.com/ElCeejo/grave/blob/main/mapgen.lua#L23)

I'll have a think about how it can be handled, I think you're right about reporting the error instead of attempting to run - it won't know what to do with that biome.

**Comment by mk-pmb** [comment]
For a lint program, that mistake would have been obvious. Even my really simple [github action to avoid stray globals](https://github.com/mk-pmb/ghaction-lua-contemn-stray-globals) would have found it. :-) However, it found hundreds of other places where it's "just" a coding style issue, and I wasn't eager to fix all of them. For you as the author, it's probably easier.

**Comment by mk-pmb** [comment]
Sorry for the confusion. I see now that actually @ElCeejo is the author of grave. I had assumed you were, from your mention that you should change your fonts.
