### ISSUE TITLE
Unknown nodes appear below the nether

### ISSUE THREAD

**Issue by Treer** [minetest-mods/nether#51]
The nodes in question are the "node_stone" of the nether_caverns biome, they just look like unknown nodes because node_stone is set to "nether:native_mapgen" and "nether:native_mapgen" has an empty definition.

I'm unsure whether this is an engine bug, or a constraint I don't understand.

With a biome defined from -5000 to -11000, the entire chunk below the biome ends up with the biome's node_stone appearing at underhangs.

The relevant chunk spans 10992 to 11072, so the node_stone appears down to 11072 even though the biome was defined with [a y_min of -11000, and has its vertical_blend set to 0](https://github.com/minetest-mods/nether/blob/52038017f385382fb43c9d0aa1e081e6618ce1aa/mapgen.lua#L191-L192).

This can be hidden by using a biome y_min of -11072 instead (i.e. align the biome boundary to the chunk boundary by setting the bottom of the nether to -11072), but I'd like to understand whether it's an engine bug or blend feature or an oversight in my understanding of biomes.

(Ignore the fact that the node_stone appears as "unknown" in the screenshot, that's unrelated and doesn't affect the issue)
![screenshot_20210705_225643_small](https://user-images.githubusercontent.com/6390507/133955507-9fce8395-aa0c-42ff-a772-d060fe2c1daf.jpg)

# To "fix"
Set the bottom of the nether to -11072 (or your nearest chunk boundary y value)

**Comment by 0siribix** [comment]
Seems like an engine bug 🤷‍♂️

**Comment by Treer** [comment]
An alias might prevent new nether chunks from generating correctly.
The purpose of nether:native_mapgen is to prevent the C++ mapgen from creating stone in the nether, because IIRC it calls its decoration routines before the nether's on_generate() is invoked, and that causes edge cases I can't recall the details of (perhaps ores or decorations crossing chunk boundaries?).
Anything that replaces nether:native_mapgen in a chunk *after* the chunk has been fully generated should be fine.

**Comment by Treer** [comment]
Existing out of place neither nodes are hidden by #72, and new nodes will no longer leak due to https://github.com/minetest/minetest/pull/13472 fixing https://github.com/minetest/minetest/issues/13440
