### ISSUE TITLE
Can you make the Nether Brick fences support the Tall fences and walls setting in Minetest Game

### ISSUE THREAD

**Issue by snowtest-sled** [minetest-mods/nether#56]
If I enable Tall fences and walls setting in Minetest Game I can still jump over Nether Brick Fences

**Comment by Treer** [comment]
Interesting, looks like MTG has [an API for making fences](https://github.com/minetest/minetest_game/blob/0c2ee1e41d71899f0d5e1da603a6d125a7cda9e9/mods/default/functions.lua#L309-L311), and nether just [never used it](https://github.com/minetest-mods/nether/blob/d3f79e961b591b322472fb7a378644ff144c5900/nodes.lua#L252-L270).
