### ISSUE TITLE
fumaroles in the overworld don't create fire, but do extinguish fire if they're near some

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/nether#59]
a player was trying to use them to add a smoking effect to a bonfire build, but the fire kept going out. it took a while to understand what was going on.

the correct behavior should probably be either:
1. fumaroles work the same in both the nether and in the "overworld"
2. fumaroles neither create nor extinguish fire in the "overworld"

i prefer #2, but i thought i'd ask before submitting a PR.

**Comment by Treer** [comment]
I agree with your #2 as well, the fire was supposed to be a nether effect so extinguishing it in the overworld is a bug,

FWIW, my thoughts behind the behaviour difference was:

- Having a block that's repurposable for e.g. cottage chimneys with quaint puffs of smokes provides a 'treasure' to go on an expedition for.
- The nether needed more danger. Someone in [issue 4](4) said "the only danger is falling down the cliff" and they had a point, so... surprise fire. Unlikely to catch anyone but perhaps it can add some atmosphere when you see it in the distance and reduce the feeling of safety when it happens nearby.
